var dataSDK = [
    {
        title:'Bmob简介及crud(增删查改)初体验',
        chapter:[
            {
                title:'Bmob数据SDK介绍及集成与初始化',
                id:'XMzEwNDcyNzQ4NA=='
            },
            {
                title:'1_1_添加一行数据1',
                id:'XMzEwOTE2MDAxMg=='
            },
            {
                title:'1_2_添加一行数据2',
                id:'XMzEwOTE4MjA5Mg=='
            },
            {
                title:'2-1_查询一行数据',
                id:'XMzEwOTI0NDcxNg=='
            },
            {
                title:'2_2_更新一行数据',
                id:'XMzEwOTIzMTI2MA=='
            },
            {
                title:'2_3_删除一行数据',
                id:'XMzEwOTI2MDI4NA=='
            }
        ]
    },
    {
        title:'crud详细使用及数据类型介绍',
        chapter:[
            {
                title:'3_1_数据对象与数据类介绍与使用1',
                id:'XMzEwOTI2NjgzMg=='
            },
            {
                title:'3_2_数据对象与数据类介绍与使用2',
                id:'XMzEwOTM3MjU2MA=='
            },
            {
                title:'4_1_自定义表名的使用',
                id:'XMzEwOTM3NTM4OA=='
            },
            {
                title:'4_2_自定义表名下的数据查询',
                id:'XMzEwOTM4ODI2MA=='
            },
            {
                title:'5_插入数据详解',
                id:'XMzEwOTM5ODM0NA=='
            },
            {
                title:'6_更新数据详解之原子计数器',
                id:'XMzEwOTQxMTcwOA=='
            },
            {
                title:'7_更新数据详解之删除字段的值',
                id:'XMzEwOTQzMzI4MA=='
            },
            {
                title:'8_批量操作详解之批量插入数据',
                id:'XMzEwOTQ0NTA0OA=='
            },
            {
                title:'9_批量操作详解之批量更新数据',
                id:'XMzEwOTY0MTEyMA=='
            },
            {
                title:'10_批量操作详解之同时提交增删改',
                id:'XMzEwOTQ5MTM5Ng=='
            },
            {
                title:'11_数据查询详解之多条数据查询1及debug小技巧',
                id:'XMzEwOTUxMDc2MA=='
            },
            {
                title:'12_1_数据查询详解之条件查询与子查询易错写法',
                id:'XMzEwOTUzMjM2OA=='
            },
            {
                title:'13_数据查询详解之时间查询',
                id:'XMzEwOTU1ODM2NA=='
            },
            {
                title:'14_数据查询详解之分页查询',
                id:'XMzEwOTU5NzQxNg=='
            },
            {
                title:'15_数据查询详解之排序',
                id:'XMzEwOTYyNDc1Ng=='
            },
            {
                title:'17_数据查询详解之查询结果计数',
                id:'XMzEwOTY1OTIxMg=='
            },
            {
                title:'18_数据查询详解之统计查询',
                id:'XMzEwOTY5NjcwOA=='
            },
            {
                title:'19_数据查询详解之分组统计',
                id:'XMzEwOTc1Njg5Ng=='
            },
            {
                title:'20_数组详解1',
                id:'XMzEwOTc4NzE0MA=='
            },
            {
                title:'21_数组详解1',
                id:'XMzEwOTgyMjExMg=='
            },
            {
                title:'22_数组详解1',
                id:'XMzEwOTgzNzM4OA=='
            }
        ]
    },
    {
        title:'数据关联详细使用',
        chapter:[
            {
                title:'23_1_数据关联详解之添加一对一关联1',
                id:'XMzEwOTg2ODE0MA=='
            },
            {
                title:'23_2_数据关联详解之添加一对一关联2',
                id:'XMzEwOTg5MzA4NA=='
            },
            {
                title:'24_数据关联详解之查询一对一关联与include',
                id:'XMzEwOTkxNDYzNg=='
            },
            {
                title:'25_数据关联详解之查询一对多关联',
                id:'XMzEwOTkzNDcwMA=='
            },
            {
                title:'26_数据关联详解之添加多对多关联',
                id:'XMzEwOTk2NDUxMg=='
            },
            {
                title:'27_数据关联详解之查询多对多关联',
                id:'XMzEwOTk3MDcwOA=='
            },
            {
                title:'28_数据关联详解之内部查询',
                id:'XMzEwOTk4ODM5Mg=='
            }
        ]
    },
    {
        title:'文件相关功能和地理位置',
        chapter:[
            {
                title:'29_1_文件上传介绍及上传单一文件常见写法',
                id:'XMzEwOTk5NDMyMA=='
            },
            {
                title:'29_2_文件上传中的常见动态权限错误展示',
                id:'XMzExMDAwNzQ4OA=='
            },
            {
                title:'29_3_文件上传之适配动态权限实现',
                id:'XMzExMDAxODI1Ng=='
            },
            {
                title:'30_文件上传之批量文件上传',
                id:'XMzExMDAyMjI4MA=='
            },
            {
                title:'31_文件详解之BmobFile和数据表的关联实现',
                id:'XMzExMTkzNDUxMg=='
            },
            {
                title:'32_1_文件详解之文件下载及错误展示',
                id:'XMzExMDA1NDcwOA=='
            },
            {
                title:'32_2_文件详解之文件下载的路径错误修正',
                id:'XMzExMDA3MTA4MA=='
            },
            {
                title:'33_文件详解之删除文件',
                id:'XMzExMDA3NDEyMA=='
            },
            {
                title:'34_地理位置相关功能详解',
                id:'XMzExMDA4NDEzNg=='
            }
        ]
    }
];


var PUSHSDK = [{
    title:'BmobPush SDK的简介和集成',
    chapter:[{
        title:'1、BmobPush SDK的简介和集成',
        id:'XMzExMTY4ODg2MA=='
    }]
},{
    title:'如何在控制台推送消息给客户端',
    chapter:[{
        title:'2、如何在控制台推送消息给客户端',
        id:'XMzExMTcyNDY0MA=='
    }]
},{
    title:'消息推送的设备信息：Installation',
    chapter:[{
        title:'3、消息推送的设备信息：Installation',
        id:'XMzExMTc0OTE1Mg=='
    }]
},{
    title:'推送频道的订阅和退订',
    chapter:[{
        title:'4、推送频道的订阅和退订',
        id:'XMzExMTg2MzY0OA=='
    }]
},{
    title:'客户端发起的消息推送',
    chapter:[{
        title:'5、客户端发起的消息推送',
        id:'XMzExMTc4NjQzMg=='
    }]
}];


var IMSDK = [{
    title:'BmobNewIM SDK 介绍',
    chapter:[{
        title:'1、BmobNewIM SDK 介绍',
        id:'XMzExMTA3NDQ0NA=='
    }]
},{
    title:'BmobNewIM SDK 集成',
    chapter:[{
        title:'2、BmobNewIM SDK 集成',
        id:'XMzExMTA3NzMzMg=='
    }]
},{
    title:'BmobNewIM SDK 使用',
    chapter:[{
        title:'3.1、BmobNewIM 案例流程图',
        id:'XMzExMTA5ODgwNA=='
    },{
        title:'3.2.1、Bmob的用户系统',
        id:'XMzExMTExNzIxMg=='
    },{
        title:'3.2.2、IM的本地用户信息',
        id:'XMzExMTEyNTc4NA=='
    },{
        title:'3.3、IM服务器的连接',
        id:'XMzExMTEzOTkyOA=='
    },{
        title:'3.4.1、创建IM的会话',
        id:'XMzExMTE1NDM2NA=='
    },{
        title:'3.4.2、IM会话其他操作',
        id:'XMzExMTE5NTE2OA=='
    },{
        title:'3.5、IM的消息类型和管理',
        id:'XMzExMTI1NTEwMA=='
    },{
        title:'3.6、IM的消息发送',
        id:'XMzExMTQyMzI4MA=='
    },{
        title:'3.7、IM的自定义消息',
        id:'XMzExMTUyMjk2OA=='
    },{
        title:'3.8、IM的消息接收',
        id:'XMzExMTU0NTEwOA=='
    },{
        title:'3.9、好友管理',
        id:'XMzExMTU3ODI5Mg=='
    }]
},{
    title:'IM SDK 的混淆和旧版回顾',
    chapter:[{
        title:'4、IM SDK 的混淆和旧版回顾',
        id:'XMzExMTY4MzI2NA=='
    }]
}]